version: "3.8"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    # restart: "always"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
