import Head from "next/head";
import SearchCep from "../components/SearchCep";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ViaCep</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-vindo ao <span>ViaCEP</span>
        </h1>

        <SearchCep />
      </main>
    </div>
  );
}
